# Generated by Django 4.0 on 2022-09-01 04:57

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Todo_User',
            fields=[
                ('id_user', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Todo_Task',
            fields=[
                ('id_task', models.AutoField(primary_key=True, serialize=False)),
                ('task', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField(auto_now_add=True)),
                ('end_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('mod_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('stat', models.BooleanField(default=False)),
                ('todo_list', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api_todo.todo_user')),
            ],
            options={
                'ordering': ('-start_date',),
            },
        ),
    ]
