# Generated by Django 4.0 on 2022-10-09 07:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api_todo', '0002_alter_todo_task_options_newuser'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewUser',
        ),
    ]
